#-------------------------------
# General Site Settings
title: NoSho
logo: # You can add own logo. For example '/images/logo.png'.
description: NoSho is all the stuff I don't want to tell people about
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://nosho.org"


#-------------------------------
# Author Settings
author:
  name: No Sho
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: NoSho
  description: NoSho is all the stuff I don't want to tell people about
  image: "" # '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: 
  description: You probably can't reach me

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: "mailchimp.us8.list-manage.com/subscribe/post?u=f80411588597079f5a27ebb4f;id=cddd58d371"


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed